<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\ProvinsiModel;
use Exception;

class LowonganMagangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1) Make sure provinsi table already has data!
        $provinsi = ProvinsiModel::all(['id','alt_name','nama']);
        if ($provinsi->isEmpty()) {
            throw new Exception("m_provinsi is empty—run ProvinsiSeeder first!");
        }

        // 2) Build two maps, normalized uppercase:
        $mapAlt  = $provinsi->pluck('id','alt_name')
                            ->mapWithKeys(fn($id,$alt)=>[strtoupper($alt)=>$id]);
        $mapNama = $provinsi->pluck('id','nama')
                            ->mapWithKeys(fn($id,$nama)=>[strtoupper($nama)=>$id]);


        // 2) Raw data: 'lokasi' pakai ALT_NAME provinsi
        $raw = [
            [
                'judul'                => 'Magang Front-End Developer',
                'deskripsi'            => 'Bekerja sebagai pengembang antarmuka pengguna web dengan HTML, CSS, dan JavaScript.',
                'tanggal_mulai_magang' => now()->addDays(10),
                'deadline_lowongan'    => now()->addDays(5),
                'lokasi'               => 'DKI JAKARTA',
                'perusahaan_id'        => 1,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_frontend.pdf',
                'status'               => 'aktif',
                'kuota'                => 3,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang Back-End Developer',
                'deskripsi'            => 'Mengembangkan API dan mengelola database menggunakan PHP/Laravel.',
                'tanggal_mulai_magang' => now()->addDays(20),
                'deadline_lowongan'    => now()->addDays(10),
                'lokasi'               => 'DKI JAKARTA',
                'perusahaan_id'        => 1,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_backend.pdf',
                'status'               => 'aktif',
                'kuota'                => 2,
                'durasi'               => 3, 
            ],
            [
                'judul'                => 'Magang Data Analyst',
                'deskripsi'            => 'Analisis data perusahaan dan membuat laporan visualisasi menggunakan Python.',
                'tanggal_mulai_magang' => now()->addDays(15),
                'deadline_lowongan'    => now()->addDays(7),
                'lokasi'               => 'DI YOGYAKARTA',
                'perusahaan_id'        => 2,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_data_analyst.pdf',
                'status'               => 'aktif',
                'kuota'                => 4,
                'durasi'               => 3, 
            ],
            [
                'judul'                => 'Magang UI/UX Designer',
                'deskripsi'            => 'Membantu mendesain antarmuka dan pengalaman pengguna untuk aplikasi web/mobile.',
                'tanggal_mulai_magang' => now()->addDays(25),
                'deadline_lowongan'    => now()->addDays(12),
                'lokasi'               => 'DI YOGYAKARTA',
                'perusahaan_id'        => 2,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_uiux.pdf',
                'status'               => 'aktif',
                'kuota'                => 2,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang Mobile Developer',
                'deskripsi'            => 'Pengembangan aplikasi Android menggunakan Kotlin.',
                'tanggal_mulai_magang' => now()->addDays(18),
                'deadline_lowongan'    => now()->addDays(9),
                'lokasi'               => 'JAWA BARAT',
                'perusahaan_id'        => 3,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_mobile_dev.pdf',
                'status'               => 'aktif',
                'kuota'                => 3,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang DevOps Engineer',
                'deskripsi'            => 'Mempelajari dan membantu pengelolaan infrastruktur CI/CD di AWS.',
                'tanggal_mulai_magang' => now()->addDays(30),
                'deadline_lowongan'    => now()->addDays(20),
                'lokasi'               => 'JAWA BARAT',
                'perusahaan_id'        => 3,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_devops.pdf',
                'status'               => 'aktif',
                'kuota'                => 2,
                'durasi'               => 3, 
            ],
            [
                'judul'                => 'Magang Data Engineer',
                'deskripsi'            => 'Mengolah pipeline data menggunakan ETL dan SQL.',
                'tanggal_mulai_magang' => now()->addDays(12),
                'deadline_lowongan'    => now()->addDays(6),
                'lokasi'               => 'JAWA TIMUR',
                'perusahaan_id'        => 4,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_data_engineer.pdf',
                'status'               => 'aktif',
                'kuota'                => 3,
                'durasi'               => 3, 
            ],
            [
                'judul'                => 'Magang Social Media Specialist',
                'deskripsi'            => 'Mengelola konten dan kampanye media sosial perusahaan.',
                'tanggal_mulai_magang' => now()->addDays(22),
                'deadline_lowongan'    => now()->addDays(11),
                'lokasi'               => 'JAWA TIMUR',
                'perusahaan_id'        => 4,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_sosmed.pdf',
                'status'               => 'aktif',
                'kuota'                => 4,
                'durasi'               => 3, 
            ],
            [
                'judul'                => 'Magang Business Analyst',
                'deskripsi'            => 'Menganalisis kebutuhan bisnis dan membuat dokumentasi proses.',
                'tanggal_mulai_magang' => now()->addDays(14),
                'deadline_lowongan'    => now()->addDays(8),
                'lokasi'               => 'JAWA TENGAH',
                'perusahaan_id'        => 5,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_business_analyst.pdf',
                'status'               => 'aktif',
                'kuota'                => 2,
                'durasi'               => 3, 
            ],
            [
                'judul'                => 'Magang Graphic Designer',
                'deskripsi'            => 'Membuat materi visual dan branding untuk klien.',
                'tanggal_mulai_magang' => now()->addDays(17),
                'deadline_lowongan'    => now()->addDays(10),
                'lokasi'               => 'JAWA TENGAH',
                'perusahaan_id'        => 5,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_graphic_designer.pdf',
                'status'               => 'aktif',
                'kuota'                => 3,
                'durasi'               => 3, 
            ],
            [
                'judul'                => 'Magang Sales & Marketing',
                'deskripsi'            => 'Membantu tim sales melakukan riset pasar dan strategi pemasaran.',
                'tanggal_mulai_magang' => now()->addDays(11),
                'deadline_lowongan'    => now()->addDays(5),
                'lokasi'               => 'BALI',
                'perusahaan_id'        => 6,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_sales_marketing.pdf',
                'status'               => 'aktif',
                'kuota'                => 4,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang Customer Service',
                'deskripsi'            => 'Menangani pertanyaan pelanggan dan meningkatkan kepuasan layanan.',
                'tanggal_mulai_magang' => now()->addDays(21),
                'deadline_lowongan'    => now()->addDays(13),
                'lokasi'               => 'BALI',
                'perusahaan_id'        => 6,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_customer_service.pdf',
                'status'               => 'aktif',
                'kuota'                => 5,
                'durasi'               => 3, 
            ],
            [
                'judul'                => 'Magang AI Research Assistant',
                'deskripsi'            => 'Membantu penelitian AI dan prototyping model machine learning.',
                'tanggal_mulai_magang' => now()->addDays(16),
                'deadline_lowongan'    => now()->addDays(8),
                'lokasi'               => 'LAMPUNG',
                'perusahaan_id'        => 7,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_ai_research.pdf',
                'status'               => 'aktif',
                'kuota'                => 2,
                'durasi'               => 3, 
            ],
            [
                'judul'                => 'Magang Software Tester',
                'deskripsi'            => 'Melakukan pengujian sistem dan pelaporan bug untuk tim QA.',
                'tanggal_mulai_magang' => now()->addDays(26),
                'deadline_lowongan'    => now()->addDays(15),
                'lokasi'               => 'LAMPUNG',
                'perusahaan_id'        => 7,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_software_tester.pdf',
                'status'               => 'aktif',
                'kuota'                => 3,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang Video Editor',
                'deskripsi'            => 'Mengedit video promosi dan konten sosial media.',
                'tanggal_mulai_magang' => now()->addDays(13),
                'deadline_lowongan'    => now()->addDays(6),
                'lokasi'               => 'BANTEN',
                'perusahaan_id'        => 8,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_video_editor.pdf',
                'status'               => 'aktif',
                'kuota'                => 3,
                'durasi'               => 3, 
            ],
            [
                'judul'                => 'Magang Animator',
                'deskripsi'            => 'Membuat animasi untuk iklan dan konten digital.',
                'tanggal_mulai_magang' => now()->addDays(23),
                'deadline_lowongan'    => now()->addDays(12),
                'lokasi'               => 'BANTEN',
                'perusahaan_id'        => 8,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_animator.pdf',
                'status'               => 'aktif',
                'kuota'                => 2,
                'durasi'               => 3, 
            ],
            [
                'judul'                => 'Magang R&D Engineer',
                'deskripsi'            => 'Mengembangkan prototipe dan melakukan eksperimen teknologi baru.',
                'tanggal_mulai_magang' => now()->addDays(19),
                'deadline_lowongan'    => now()->addDays(9),
                'lokasi'               => 'SULAWESI UTARA',
                'perusahaan_id'        => 9,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_rnd_engineer.pdf',
                'status'               => 'aktif',
                'kuota'                => 2,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang IT Support',
                'deskripsi'            => 'Memberikan dukungan teknis dan pemeliharaan sistem jaringan.',
                'tanggal_mulai_magang' => now()->addDays(29),
                'deadline_lowongan'    => now()->addDays(18),
                'lokasi'               => 'SULAWESI UTARA',
                'perusahaan_id'        => 9,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_it_support.pdf',
                'status'               => 'aktif',
                'kuota'                => 4,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang Cloud Infrastructure',
                'deskripsi'            => 'Mempelajari setup dan manajemen infrastruktur cloud (AWS/GCP).',
                'tanggal_mulai_magang' => now()->addDays(21),
                'deadline_lowongan'    => now()->addDays(11),
                'lokasi'               => 'NUSA TENGGARA BARAT',
                'perusahaan_id'        => 10,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_cloud_infra.pdf',
                'status'               => 'aktif',
                'kuota'                => 2,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang Network Engineer',
                'deskripsi'            => 'Membantu pengaturan dan pemeliharaan jaringan perusahaan.',
                'tanggal_mulai_magang' => now()->addDays(31),
                'deadline_lowongan'    => now()->addDays(16),
                'lokasi'               => 'NUSA TENGGARA BARAT',
                'perusahaan_id'        => 10,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_network_engineer.pdf',
                'status'               => 'aktif',
                'kuota'                => 3,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang QA Automation Tester',
                'deskripsi'            => 'Mendesain dan mengimplementasikan skrip automatisasi pengujian.',
                'tanggal_mulai_magang' => now()->addDays(14),
                'deadline_lowongan'    => now()->addDays(7),
                'lokasi'               => 'SUMATERA SELATAN',
                'perusahaan_id'        => 11,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_qa_automation.pdf',
                'status'               => 'aktif',
                'kuota'                => 2,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang Security Analyst',
                'deskripsi'            => 'Menganalisis kerentanan sistem dan membantu tim keamanan.',
                'tanggal_mulai_magang' => now()->addDays(17),
                'deadline_lowongan'    => now()->addDays(9),
                'lokasi'               => 'SUMATERA SELATAN',
                'perusahaan_id'        => 11,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_security_analyst.pdf',
                'status'               => 'aktif',
                'kuota'                => 3,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang Blockchain Developer',
                'deskripsi'            => 'Mengembangkan smart contract di Ethereum menggunakan Solidity.',
                'tanggal_mulai_magang' => now()->addDays(20),
                'deadline_lowongan'    => now()->addDays(10),
                'lokasi'               => 'KEPULAUAN RIAU',
                'perusahaan_id'        => 12,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_blockchain_dev.pdf',
                'status'               => 'aktif',
                'kuota'                => 2,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang IoT Engineer',
                'deskripsi'            => 'Membantu implementasi solusi IoT pada perangkat embedded.',
                'tanggal_mulai_magang' => now()->addDays(24),
                'deadline_lowongan'    => now()->addDays(14),
                'lokasi'               => 'KEPULAUAN RIAU',
                'perusahaan_id'        => 12,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_iot_engineer.pdf',
                'status'               => 'aktif',
                'kuota'                => 3,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang Game Developer',
                'deskripsi'            => 'Membuat prototipe game 2D/3D menggunakan Unity.',
                'tanggal_mulai_magang' => now()->addDays(16),
                'deadline_lowongan'    => now()->addDays(8),
                'lokasi'               => 'NUSA TENGGARA TIMUR',
                'perusahaan_id'        => 13,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_game_dev.pdf',
                'status'               => 'aktif',
                'kuota'                => 4,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang QA Tester',
                'deskripsi'            => 'Melakukan pengujian fungsional dan regresi pada aplikasi software.',
                'tanggal_mulai_magang' => now()->addDays(28),
                'deadline_lowongan'    => now()->addDays(17),
                'lokasi'               => 'NUSA TENGGARA TIMUR',
                'perusahaan_id'        => 13,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_qa_tester.pdf',
                'status'               => 'aktif',
                'kuota'                => 3,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang SEO Specialist',
                'deskripsi'            => 'Mengoptimasi konten agar muncul di peringkat atas mesin pencari.',
                'tanggal_mulai_magang' => now()->addDays(12),
                'deadline_lowongan'    => now()->addDays(6),
                'lokasi'               => 'KALIMANTAN BARAT',
                'perusahaan_id'        => 14,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_seo_specialist.pdf',
                'status'               => 'aktif',
                'kuota'                => 2,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang Content Writer',
                'deskripsi'            => 'Menulis artikel dan konten blog sesuai kebutuhan perusahaan.',
                'tanggal_mulai_magang' => now()->addDays(18),
                'deadline_lowongan'    => now()->addDays(9),
                'lokasi'               => 'KALIMANTAN BARAT',
                'perusahaan_id'        => 14,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_content_writer.pdf',
                'status'               => 'aktif',
                'kuota'                => 3,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang Project Manager',
                'deskripsi'            => 'Membantu perencanaan dan pengelolaan proyek TI.',
                'tanggal_mulai_magang' => now()->addDays(15),
                'deadline_lowongan'    => now()->addDays(7),
                'lokasi'               => 'DI YOGYAKARTA',
                'perusahaan_id'        => 15,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_project_manager.pdf',
                'status'               => 'aktif',
                'kuota'                => 2,
                'durasi'               => 6, 
            ],
            [
                'judul'                => 'Magang Business Development',
                'deskripsi'            => 'Mendukung tim BD dalam riset pasar dan klien.',
                'tanggal_mulai_magang' => now()->addDays(27),
                'deadline_lowongan'    => now()->addDays(13),
                'lokasi'               => 'DI YOGYAKARTA',
                'perusahaan_id'        => 15,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_business_development.pdf',
                'status'               => 'aktif',
                'kuota'                => 4,
                'durasi'               => 6, 
            ],
        ];

        // 4) Convert each lokasi → provinsi.id
        $toInsert = array_map(function($item) use ($mapAlt, $mapNama) {
            $key = strtoupper($item['lokasi']);

            if (isset($mapAlt[$key])) {
                $item['lokasi'] = $mapAlt[$key];
            }
            elseif (isset($mapNama[$key])) {
                $item['lokasi'] = $mapNama[$key];
            }
            else {
                throw new Exception("Provinsi not found for '{$item['lokasi']}'");
            }

            return $item;
        }, $raw);

        // 5) Bulk insert
        DB::table('t_lowongan_magang')->insert($toInsert);
    }
}
